export const FETCH_DASHBOARD_RESPONSE_REQUEST =
  "FETCH_DASHBOARD_RESPONSE_REQUEST";
export const FETCH_DASHBOARD_RESPONSE_SUCCESS =
  "FETCH_DASHBOARD_RESPONSE_SUCCESS";
export const FETCH_DASHBOARD_RESPONSE_FAILED =
  "FETCH_DASHBOARD_RESPONSE_FAILED";

export const FETCH_SUB_BREED_REQUEST = "FETCH_SUB_BREED_REQUEST";
export const FETCH_SUB_BREED_SUCCESS = "FETCH_SUB_BREED_SUCCESS";
export const FETCH_SUB_BREED_FAILED = "FETCH_SUB_BREED_FAILED";

export const FETCH_BREED_IMAGES_REQUEST = "FETCH_BREED_IMAGES_REQUEST";
export const FETCH_BREED_IMAGES_SUCCESS = "FETCH_BREED_IMAGES_SUCCESS";
export const FETCH_BREED_IMAGES_FAILED = "FETCH_BREED_IMAGES_FAILED";
